### PR TITLE
Successfully compile to pcl-1.11.1, pcl-ros-1.7.2 and g20-20201223_git

### PR DESCRIPTION
**Pull request by AchmadFathoni**
Well, of course the CI will not successfully build this PR because the old package they have. I build this on bleeding edge Arch. I hope this PR will be useful as future reference when those new version packages is released in noetic.

### CODE REVIEW

**Comment by koide3** [comment]
Thanks! Can we avoid the ```shared_ptr``` errors by using ```pcl::shared_ptr```?

**Comment by AchmadFathoni** [comment]
Changed to `pcl::shared_ptr`

**Comment by AchmadFathoni** [comment]
I think this PR does to much think so I separate the transition of shared_ptr to https://github.com/koide3/hdl_graph_slam/pull/192

**Comment by koide3** [comment]
Thanks for your contribution. I merge it :+1:

**Pull request merged**
